/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LegalMentionsRouteImport } from './routes/legal.mentions'
import { Route as LegalConfidentialiteRouteImport } from './routes/legal.confidentialite'
import { Route as LegalCguRouteImport } from './routes/legal.cgu'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedAccountRouteImport } from './routes/_authenticated/account'
import { Route as ApiPublicProcessAlertsRouteImport } from './routes/api/public/process-alerts'
import { Route as ApiPublicPositionsRouteImport } from './routes/api/public/positions'
import { Route as AuthenticatedDevicesNewRouteImport } from './routes/_authenticated/devices.new'
import { Route as AuthenticatedDevicesIdRouteImport } from './routes/_authenticated/devices.$id'
import { Route as ApiPublicAuthRateCheckRouteImport } from './routes/api/public/auth.rate-check'

const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalMentionsRoute = LegalMentionsRouteImport.update({
  id: '/legal/mentions',
  path: '/legal/mentions',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalConfidentialiteRoute = LegalConfidentialiteRouteImport.update({
  id: '/legal/confidentialite',
  path: '/legal/confidentialite',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalCguRoute = LegalCguRouteImport.update({
  id: '/legal/cgu',
  path: '/legal/cgu',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAccountRoute = AuthenticatedAccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const ApiPublicProcessAlertsRoute = ApiPublicProcessAlertsRouteImport.update({
  id: '/api/public/process-alerts',
  path: '/api/public/process-alerts',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicPositionsRoute = ApiPublicPositionsRouteImport.update({
  id: '/api/public/positions',
  path: '/api/public/positions',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedDevicesNewRoute = AuthenticatedDevicesNewRouteImport.update({
  id: '/devices/new',
  path: '/devices/new',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDevicesIdRoute = AuthenticatedDevicesIdRouteImport.update({
  id: '/devices/$id',
  path: '/devices/$id',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const ApiPublicAuthRateCheckRoute = ApiPublicAuthRateCheckRouteImport.update({
  id: '/api/public/auth/rate-check',
  path: '/api/public/auth/rate-check',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/account': typeof AuthenticatedAccountRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/legal/cgu': typeof LegalCguRoute
  '/legal/confidentialite': typeof LegalConfidentialiteRoute
  '/legal/mentions': typeof LegalMentionsRoute
  '/devices/$id': typeof AuthenticatedDevicesIdRoute
  '/devices/new': typeof AuthenticatedDevicesNewRoute
  '/api/public/positions': typeof ApiPublicPositionsRoute
  '/api/public/process-alerts': typeof ApiPublicProcessAlertsRoute
  '/api/public/auth/rate-check': typeof ApiPublicAuthRateCheckRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/account': typeof AuthenticatedAccountRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/legal/cgu': typeof LegalCguRoute
  '/legal/confidentialite': typeof LegalConfidentialiteRoute
  '/legal/mentions': typeof LegalMentionsRoute
  '/devices/$id': typeof AuthenticatedDevicesIdRoute
  '/devices/new': typeof AuthenticatedDevicesNewRoute
  '/api/public/positions': typeof ApiPublicPositionsRoute
  '/api/public/process-alerts': typeof ApiPublicProcessAlertsRoute
  '/api/public/auth/rate-check': typeof ApiPublicAuthRateCheckRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/_authenticated/account': typeof AuthenticatedAccountRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/legal/cgu': typeof LegalCguRoute
  '/legal/confidentialite': typeof LegalConfidentialiteRoute
  '/legal/mentions': typeof LegalMentionsRoute
  '/_authenticated/devices/$id': typeof AuthenticatedDevicesIdRoute
  '/_authenticated/devices/new': typeof AuthenticatedDevicesNewRoute
  '/api/public/positions': typeof ApiPublicPositionsRoute
  '/api/public/process-alerts': typeof ApiPublicProcessAlertsRoute
  '/api/public/auth/rate-check': typeof ApiPublicAuthRateCheckRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/reset-password'
    | '/account'
    | '/dashboard'
    | '/legal/cgu'
    | '/legal/confidentialite'
    | '/legal/mentions'
    | '/devices/$id'
    | '/devices/new'
    | '/api/public/positions'
    | '/api/public/process-alerts'
    | '/api/public/auth/rate-check'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/reset-password'
    | '/account'
    | '/dashboard'
    | '/legal/cgu'
    | '/legal/confidentialite'
    | '/legal/mentions'
    | '/devices/$id'
    | '/devices/new'
    | '/api/public/positions'
    | '/api/public/process-alerts'
    | '/api/public/auth/rate-check'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/reset-password'
    | '/_authenticated/account'
    | '/_authenticated/dashboard'
    | '/legal/cgu'
    | '/legal/confidentialite'
    | '/legal/mentions'
    | '/_authenticated/devices/$id'
    | '/_authenticated/devices/new'
    | '/api/public/positions'
    | '/api/public/process-alerts'
    | '/api/public/auth/rate-check'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  LegalCguRoute: typeof LegalCguRoute
  LegalConfidentialiteRoute: typeof LegalConfidentialiteRoute
  LegalMentionsRoute: typeof LegalMentionsRoute
  ApiPublicPositionsRoute: typeof ApiPublicPositionsRoute
  ApiPublicProcessAlertsRoute: typeof ApiPublicProcessAlertsRoute
  ApiPublicAuthRateCheckRoute: typeof ApiPublicAuthRateCheckRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal/mentions': {
      id: '/legal/mentions'
      path: '/legal/mentions'
      fullPath: '/legal/mentions'
      preLoaderRoute: typeof LegalMentionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal/confidentialite': {
      id: '/legal/confidentialite'
      path: '/legal/confidentialite'
      fullPath: '/legal/confidentialite'
      preLoaderRoute: typeof LegalConfidentialiteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal/cgu': {
      id: '/legal/cgu'
      path: '/legal/cgu'
      fullPath: '/legal/cgu'
      preLoaderRoute: typeof LegalCguRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/account': {
      id: '/_authenticated/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AuthenticatedAccountRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/public/process-alerts': {
      id: '/api/public/process-alerts'
      path: '/api/public/process-alerts'
      fullPath: '/api/public/process-alerts'
      preLoaderRoute: typeof ApiPublicProcessAlertsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/positions': {
      id: '/api/public/positions'
      path: '/api/public/positions'
      fullPath: '/api/public/positions'
      preLoaderRoute: typeof ApiPublicPositionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/devices/new': {
      id: '/_authenticated/devices/new'
      path: '/devices/new'
      fullPath: '/devices/new'
      preLoaderRoute: typeof AuthenticatedDevicesNewRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/devices/$id': {
      id: '/_authenticated/devices/$id'
      path: '/devices/$id'
      fullPath: '/devices/$id'
      preLoaderRoute: typeof AuthenticatedDevicesIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/public/auth/rate-check': {
      id: '/api/public/auth/rate-check'
      path: '/api/public/auth/rate-check'
      fullPath: '/api/public/auth/rate-check'
      preLoaderRoute: typeof ApiPublicAuthRateCheckRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAccountRoute: typeof AuthenticatedAccountRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedDevicesIdRoute: typeof AuthenticatedDevicesIdRoute
  AuthenticatedDevicesNewRoute: typeof AuthenticatedDevicesNewRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAccountRoute: AuthenticatedAccountRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedDevicesIdRoute: AuthenticatedDevicesIdRoute,
  AuthenticatedDevicesNewRoute: AuthenticatedDevicesNewRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  LegalCguRoute: LegalCguRoute,
  LegalConfidentialiteRoute: LegalConfidentialiteRoute,
  LegalMentionsRoute: LegalMentionsRoute,
  ApiPublicPositionsRoute: ApiPublicPositionsRoute,
  ApiPublicProcessAlertsRoute: ApiPublicProcessAlertsRoute,
  ApiPublicAuthRateCheckRoute: ApiPublicAuthRateCheckRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
